title: TaeminKIM Homepage
page-top-title: Taemin KIM
top-section-bg-text: Artificial Intelligence
home-subtitle: Taemin KIM&ensp;|&ensp;AI Researcher
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
